### ISSUE TITLE
Foam fade is frame rate dependent

### ISSUE THREAD

**Issue by the-mr-matt** [wave-harmonic/crest#705] opened 2020-11-28 19:38 UTC
**Describe the bug**
The rate at which foam fades in my build appears to be dependent on the frame rate. When I enable VSync, frame rate is approx 60 fps. In this case, foam fades quickly. When VSync is disabled frame rate is approx 200-300. In this case, foam fades very slowly, and appears almost permanent.

Note, in the video below there are no cuts, the only thing that changed is the frame rate.

**Screenshots / video**
https://www.dropbox.com/s/0x22ww89zw1rqr8/Crest%20Foam%20Frame%20Rate%20Issue.mp4?dl=0

**Log**
[Player.log](https://github.com/crest-ocean/crest/files/5611130/Player.log)

**Versions**
HDRP 8.2.0, Unity 2020.1.13f1

**To Reproduce**
Appears to be reproducible by any method that alters frame rate. Both VSync and Application.targetFrameRate worked for me.

**Platform**
Windows standalone

**Hardware**
RTX 2080Ti
Ryzen 3700X
32gb RAM
SSD

**Comment by huwb** [comment] 2020-12-02 07:49
I wonder if the problem is the precision of the foam data - its 8bit by default and maybe at high frame rates the delta is less than 1<256 . i'd have to think about how to solve this kind of thing.

We have the precision exposed in the foam settings - could you try creating a sim settings foam asset and attaching it to the ocean component, and increasing the foam texture precision to R16?

**Comment by the-mr-matt** [comment] 2020-12-15 01:11
I played with different configurations of precision, compression and mip maps but none seemed to have much affect.

**Comment by holdingjason** [comment] 2020-12-19 16:56
Anything to do with this one?

https://github.com/crest-ocean/crest/issues/408

**Comment by huwb** [comment] 2021-01-22 12:24
I have a test/experimental PR which locks simulation rate, which should help with this. feedback welcome

https://github.com/crest-ocean/crest/pull/734

**Comment by huwb** [comment] 2021-03-20 21:25
Will be fixed in 4.9

**Comment by daleeidd** [comment] 2021-03-24 18:40
4.9 has been released which solves this issue. The simulation may produce different results so tweaking may be required. Let us know if it can be improved.

**Closed by daleeidd** 2021-03-24 18:40 UTC
