### ISSUE TITLE
Ocean not rendering properly using orthographic camera 

### ISSUE THREAD

**Issue by neverender** [wave-harmonic/crest#426] opened 2020-02-29 00:13 UTC
**Describe the bug**
Using orthographic camera, ocean should show up on top of terrain. But it looks like the terrain renders on top of the ocean instead, even though terrain is positioned below the ocean.

**Screenshots / video**
I'm rendering to a texture here but that's not necessary to reproduce
Perspective camera works as expected:
![persp](https://user-images.githubusercontent.com/111049/75594869-2e08f580-5a3f-11ea-8bf9-775eb8f389ce.png)

Here's orthographic. Where is the blue color? Where is the foam?:
![ortho](https://user-images.githubusercontent.com/111049/75594890-3d883e80-5a3f-11ea-81c0-b1108d5c701c.png)

And here's orthographic with the terrain disabled. There's the blue color and foam! It was under the terrain?:
![ortho_no_terrain](https://user-images.githubusercontent.com/111049/75594926-5db7fd80-5a3f-11ea-9cc6-e64b448cc0e2.png)
**Log**
nope

**Versions**
Using Unity 2019.3.1f1 and built-in pipeline

**To Reproduce**
Put terrain in scene
Put Crest in scene positioned above terrain
Change camera to orthographic and look down

**Platform**
 - Editor/Windows

**Hardware**
Mobile gtx 1050

**Additional context**
nope

**Comment by moosichu** [comment] 2020-02-29 08:45
Hi @neverender,

Crest was never really intended to be used with orthographic cameras so it's not something we've previously tested for. 

However, saying that, we have been able to reproduce the issue so I will have a look at it when we have the time.

**Comment by huwb** [comment] 2020-02-29 10:17
A thought for later - it may be refraction code that breaks with orthographic. We should try disabling options on the ocean material like transparency to narrow it down when we do look at this.

**Comment by Chris1234567899** [comment] 2020-08-08 14:18
Any news on this?

**Comment by daleeidd** [comment] 2020-08-09 14:56
I had a look and it appears transparency is the issue. It may have something to do with getting results from depth buffer. The workaround for now would be to disable transparency for orthographic cameras.

**Comment by Tharaxis** [comment] 2021-01-03 20:21
Want to add my voice behind adding support for orthographic cameras. I'm working on an old-school isometric RPG and Crest seemed like the ideal option. I was so disappointed when it proceeded to not work with my camera setup.

**Comment by daleeidd** [comment] 2021-01-05 00:56
@Tharaxis I recall on discord that you are using this for HDRP, but I just looked and [HDRP only partially supports orthographic](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.2/manual/HDRP-Camera.html?q=orthographic) and [Unity recommends using URP for orthographic games](https://forum.unity.com/threads/hdrp-orthographic-mode-issues.892330/#post-5870593). So subsequently we will most likely be following Unity and will only be adding orthographic support for built-in and URP.

**Comment by Tharaxis** [comment] 2021-01-05 07:16
@daleeidd that's really unfortunate. I understand the decision, but if you're doing it in the one isn't it possible just to make it available in both? What if I'm okay with the limitations of using HDRP with an orthographic camera?

**Comment by daleeidd** [comment] 2021-01-05 15:53
@Tharaxis We'll see how we go. I'll update this with which pipelines will get orthographic support

**Comment by daleeidd** [comment] 2021-01-16 22:33
Crest 4.8 will get orthographic support for all pipelines. It looked good enough for HDRP surprisingly.

**Comment by huwb** [comment] 2021-01-16 22:36
Great work Dale

**Comment by Tharaxis** [comment] 2021-01-16 22:39
Awesome.

**Comment by daleeidd** [comment] 2021-02-01 19:33
4.8 is out. I'll close this one. If there was something we missed or someway to improve it, please open an issue.

**Closed by daleeidd** 2021-02-01 19:33 UTC
Labels: bug
