### ISSUE TITLE
Problems when rendering

### ISSUE THREAD

**Issue by vcalazas** [wave-harmonic/crest#1104] opened 2023-01-29 06:11 UTC
### Description

Describe the bug
I tried to generate a build for android phones, but even before continuing, I noticed that the water shaders have very visible stripes, as in the images below:

![Capturar4](https://user-images.githubusercontent.com/22615298/215308264-49f18ecb-0152-4201-a221-3f21e3b9adfe.PNG)

![Capturar](https://user-images.githubusercontent.com/22615298/215308269-d4dc51f3-a216-4679-acaa-7b6238a49978.PNG)

![Capturar5](https://user-images.githubusercontent.com/22615298/215308376-9fee6117-5191-48d4-b68f-c351bc338776.PNG)

When inspecting the materials, they look like this:

![Capturar3](https://user-images.githubusercontent.com/22615298/215308267-e5bd990d-b5ec-42f1-956d-7bbfefc42a27.PNG)
![Capturar2](https://user-images.githubusercontent.com/22615298/215308268-6fd6f27a-75da-4072-806c-21bc8db9e706.PNG)

All I modified from this scene was the ocean stuff:

![Capturar6](https://user-images.githubusercontent.com/22615298/215308379-49de2d19-569e-4778-bdf6-ac0c51f86622.PNG) 

Versions
Unity 2021.3.17F1 , platform Android

to reproduce
How can developers reproduce this bug?

Start a new URP project and change platform to Android, download and import Crest assets for URP. When opening any example asset scene you may notice this error.

Include steps to reproduce the behavior, with example content ideally so we can follow the steps on our side.
Android build target

Platform 
Android

Publisher or independent?
Android .apk

**Comment by daleeidd** [comment] 2023-02-02 06:59
I believe this is a duplicate of #1040. There is a potential solution at the bottom of the thread.

**Closed by daleeidd** 2023-02-02 06:59 UTC
Labels: Duplicate
