### ISSUE TITLE
[URP] Camera render gray material

### ISSUE THREAD

**Issue by Fqlox** [wave-harmonic/crest#669] opened 2020-10-18 19:58 UTC
The ocean material seems normal on viewport. It turns into a grey "unlit" material when the game is playing. 

View on viewport
![urp_shader1](https://user-images.githubusercontent.com/33659731/96378438-378ccc80-118c-11eb-9f06-412cd8012541.PNG)
View in-game
![upr_shader_gaemode](https://user-images.githubusercontent.com/33659731/96378439-39ef2680-118c-11eb-8281-917b44fd6367.PNG)

I'm running it on:
Windows 10 
Unity 2020.1.8
URP 8.2.0
Crest v4.5

**Comment by daleeidd** [comment] 2020-10-18 20:14
Thank you for reporting. By view in-game you mean in a build or just the game view? Have you set up the pipeline correctly as per the Crest manual?

**Comment by Fqlox** [comment] 2020-10-19 10:27
The view in game and build give the gray render. I've set up the setting following the youtube tutorial https://www.youtube.com/watch?v=TpJf13d_-3E

**Comment by daleeidd** [comment] 2020-10-19 15:16
Does it happen in the main example scene? Which version of Crest?

**Comment by Fqlox** [comment] 2020-10-19 16:28
Sorry it was in this video https://www.youtube.com/watch?v=qsgeG4sSLFw
I'm using v4.5. also tried on Unity 2019.4.12, got the same result. 
examples from the Creast-Example directory seems fine (I tried PirateCove Day scene).

**Comment by daleeidd** [comment] 2020-10-19 20:34
The first video is more relevant for setting up URP for Crest.

> examples from the Creast-Example directory seems fine (I tried PirateCove Day scene)

So it sounds like there is something wrong or some incompatibility with your scene. Have you tried narrowing it down by removing everything but Crest in the scene? Or creating a new scene with only Crest?

I have seen something like this before. But cannot remember the cause. Pretty sure it was for VR/XR though.

**Comment by Fqlox** [comment] 2020-10-20 10:54
I don't have anything on the scene except Crest Ocean and few objects. I changed the skybox and got a flat bluish ocean in my viewport - still grey in-game mode. I don't get any logs. l already tried making a new project but it did not resolve the issue 
![upr_shader4](https://user-images.githubusercontent.com/33659731/96576846-079c1100-12d3-11eb-935f-21b1aff9a6c7.PNG)

**Comment by daleeidd** [comment] 2020-10-20 19:02
Can you please provide a minimal project exhibiting the issue?

**Comment by Fqlox** [comment] 2020-10-21 14:50
I don't know how to send it to you: the project weights 2gb mainly because of the packages, not the scene.

**Comment by daleeidd** [comment] 2020-10-21 16:06
It shouldn't be too large if you only provide the following:

_/Assets_
_/ProjectSettings_
_/Packages_

The _Packages_ folder shouldn't contain any packages. It should only contain _manifest.json_ and possibly _packages-lock.json_ for a new project.

**Comment by Fqlox** [comment] 2020-10-21 16:30
[OCEAN_URP_2020.zip](https://github.com/crest-ocean/crest/files/5417367/OCEAN_URP_2020.zip)

Here you go

**Comment by daleeidd** [comment] 2020-10-21 23:41
Thanks. I have downloaded the file and reproduced. Will get back to you once I have a further look.

**Comment by daleeidd** [comment] 2020-10-22 23:35
So the issue is that not all of your pipeline settings has the correct options enabled (opaque and depth texture).

Strange though. I added our demo camera and it was fine. If I changed the AA from SMAA to FXAA or None on the camera, the issue appeared again. It looked as though it also changed the quality level too (to one without the correct options) which is bizarre.

Let me know if this solves the issue.

**Comment by huwb** [comment] 2020-10-26 07:08
Maybe smaa forces urp to render a depth texture which makes it work, or something like that. I think there is logic where it can include a depth texture when needed, regardless of asset config. Not sure if that's the case here though.

**Comment by Fqlox** [comment] 2020-10-27 17:50
My URP asset (URP_ file in Settings) had Depth and Opaque texture enabled. 
Also I deleted previous ocean to add another one and I've got an message error from console : 

`NullReferenceException: Object reference not set to an instance of an object
Crest.OceanRenderer.RunUpdate () (at D:/users/Felix/Documents/Projet Unity/ocean/OCEAN_UPR/Assets/Crest/Crest/Scripts/OceanRenderer.cs:684)
Crest.OceanRenderer.EditorUpdate () (at D:/users/Felix/Documents/Projet Unity/ocean/OCEAN_UPR/Assets/Crest/Crest/Scripts/OceanRenderer.cs:402)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <9ddd600ae5964fe0b21a870e08c53748>:0`

**Comment by daleeidd** [comment] 2020-10-27 19:31
> Maybe smaa forces urp to render a depth texture which makes it work, or something like that. I think there is logic where it can include a depth texture when needed, regardless of asset config. Not sure if that's the case here though.

That could be it. I'll see if we can do something similar or at validate it.

> My URP asset (URP_ file in Settings) had Depth and Opaque texture enabled.

@Fqlox look under _Project Settings > Quality_ and you should see multiple quality levels with URP assets assigned to them. These are the asset files being used.

> Also I deleted previous ocean to add another one and I've got an message error from console

That error looks like the ocean material or viewpoint is null. Most likely the latter. Will have this fixed too. Thanks.

**Comment by bpfilms** [comment] 2021-01-31 15:20
So I am trying to use this asset in a VR project but I can't find where you address which scripts to attach to the camera (if any). I've tried to replicate the Main Camera you have but it's not working. How can one use your asset in VR? It looks great until I hit "play" and then the ocean turns GRAY. I'm trying to use this with Oculus Quest and the OVR Camera Rig but I can use an XR rig if need be. Thanks!

**Comment by daleeidd** [comment] 2021-02-09 20:13
@bpfilms The issue is the depth and/or opaque texture not being enabled. The file you want to change is the [Universal Render Pipeline Asset](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.5/manual/universalrp-asset.html). Unity's instructions can be found [here](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.5/manual/configuring-universalrp-for-use.html).

**Comment by bpfilms** [comment] 2021-02-09 22:22
Thank you! I let you know how it works when I get a chance to try it out.
Appreciate the quick response!

**Comment by daleeidd** [comment] 2021-02-11 23:47
We'll be forcing opaque and depth texture dynamically in the editor if transparency or underwater is enabled. It will also warn users if the textures are forced so they can enable them correctly. Otherwise, there will be a grey or invisible ocean in build. :)

Will be out for 4.9.

**Comment by daleeidd** [comment] 2021-03-24 18:34
4.9 has been released which mitigates this issue. If you see grey ocean in builds, then enable opaque and depth texture on the URP asset.

**Closed by daleeidd** 2021-03-24 18:34 UTC
Labels: URP, question
