### ISSUE TITLE
Making Depth Cache Attenuation Developer Friendly

### ISSUE THREAD

**Issue by GXMark** [wave-harmonic/crest#726] opened 2021-01-15 21:35 UTC
Currently to make waves attenuate correctly a terrain mesh needs to be approximately 500m - 1000m before the sea level as per advised in the video https://www.youtube.com/watch?v=jcmqUlboTUk

This is not a very practical approach for terrain construction and remains a chore for the developer to have to design or take an existing terrain and adjust it for these depth heights.

What is required is a workflow as follows to accomplish something much more dev friendly 👍 

1.  Create Depth Cache Game Object 
2.  Adjust it to average height of the sea level ( e.g. 50m )
3.  Set Maximum Attenuation Depth Property on the Ocean Depth Cache component   e.g. ( 50m )
4.  Note that this is 50m lower than the sea level ( e.g. 50m ) which means the calculated world coordinate depth is 0m
     ( This will ensure that the maximum amplitude for a wave will occur at the maximum Attenuation Depth )

This workflow will ensure that existing terrains are easy compatible with the crest ocean system.

**Comment by huwb** [comment] 2021-01-19 10:54
a couple of ideas:

* depth cache input could have a option to fade down to max depth at the sides. so you could specify eg 25m, and over that distance the depths lerp down to 'deep'
* or maybe the issue is that more control is needed over how the attenuation happens. maybe there should be a scale value so that you can still get big wavelengths in shallow water

thoughts?

**Comment by GXMark** [comment] 2021-01-21 12:02
I have been thinking about this process in more depth especially since you mentioned lerping down to deep.

I don't think it is necessarily a good idea to base the depth cache off the terrain as it is inherently tedious to shape it to suit the need of the waves.  What if we use a transform position with a component to specify what the depth should be.   Each transform effectively creates a position and depth which would require  some interpolation between the positions to dynamically build the depth cache.   This is very powerful approach because it disassociates the terrain shape from the depth cache thus removing terrain design difficulties from the solution.

Is it possible to interpolate between a set of adjacent transform points with assigned depths within a 2D grid space to create a depth cache ?

your thoughts?

**Comment by huwb** [comment] 2021-01-21 12:28
its straightforward to provide your own shape - for example you could deform a plane in blender as desired, then it can be brought in and assigned to a particular layer like "SeabedProxy" or such and the depth cache can be configured to render this later.

more crudely one could also kitbash together a bunch of unity primitives to create the shape, or similar quick and dirty approaches.

a third avenue would be to use ProBuilder so you can work entirely in Unity. i found it to be slightly ropey but its probably good enough for this

**Comment by GXMark** [comment] 2021-01-21 12:46
Yes putting together a mesh offline / build time is an approach but the transform depth approach enables the ability for the depth cache to be created at runtime.  This would provide support not only for the build time dev community but also the runtime dynamic dev community building mmorg/rpg style games where terrains may well be created / terraformed in world.

**Comment by huwb** [comment] 2021-01-28 07:23
Yeah that would be an option. Would take some work, to build and to maintain. 

I think the idea on your original post, or something similar, is with trying first. I think there's a good chance that simply relaxing the relationship between depth and wave attenuation could solve the problem.

**Comment by olavrv** [comment] 2021-11-18 10:12
A smooth transition from calm to uncalm waters is a great feature in the depth cache system. Really hope you can get this in. Could even be the possibility to edit this in the depth cache texture map in photoshop for example...

**Comment by daleeidd** [comment] 2022-03-02 20:17
We've gone with #946 which is similar to solution mentioned in OP which has been merged and released with 4.15.

If another solution is needed, please open a separate issue detailing why it would be needed compared to #946.

Thank you for reporting this to us.

**Closed by daleeidd** 2022-03-02 20:17 UTC
Labels: enhancement
