### ISSUE TITLE
[Built-In RP] Shadow data doesn't work when using deferred rendering

### ISSUE THREAD

**Issue by JJarvis89** [wave-harmonic/crest#198] opened 2019-03-14 14:39 UTC
Hi again,

I am having issues getting shadows to work propertly with our project. I am having strange issues especially with shoreline foam which turns dark grey depending on the LOD level but also where I move the camera. 

The video below demonstrates this issue:
https://drive.google.com/file/d/1Md7DNP22_hUdrZtIyLkfGhvOF_pWNsG5/view?usp=sharing

The camera is set up to deferred rendering. The screenshots attached also show the settings I'm currently using. Do you have any idea what could be causing this? 

Let me know if you need any other information.

Thanks for any help!

![OceanRenderer](https://user-images.githubusercontent.com/36915689/54365384-06265380-466f-11e9-91da-a7b8a81c0e2d.PNG)

![OceanShadowSettings](https://user-images.githubusercontent.com/36915689/54365468-2e15b700-466f-11e9-9e90-068a87f67e53.PNG)

**Comment by huwb** [comment] 2019-03-17 09:27
Hm thats odd. The "shadow data" should only affect the water colour but could you try turning it off just in case (disabling Create Shadow Data). Something looks off in the shadow buffer visualisation.

Could also try disabling "3D Foam Lighting" on the ocean material and seeing what it looks like?

**Comment by huwb** [comment] 2019-04-10 06:34
Had this reported by others - turns out the shadows dont work when using built-in RP and deferred shading. I'll update the title.

**Comment by JJarvis89** [comment] 2019-04-10 06:42
Sorry for not getting back to you. I must have missed your response. Thanks for having a look at it!

**Comment by huwb** [comment] 2019-04-10 06:54
Np! You're welcome although the bad news is that this is in the middle of the line of things to do, a line in which other things keep pushing in. I hope to take a look at this soon, but thought it best to communicate that.

**Comment by huwb** [comment] 2019-05-05 16:00
This has fallen further down my todo list I'm sorry to say :(. I have to prioritise support for paid assets and also development of HDRP, so I need to lean on the community for this one. I'll apply the "help needed" tag.

**Comment by alomo01** [comment] 2020-01-27 18:16
When using deferred, it seems like __ShadowMapTexture_ isn't being set.

I'm getting the error:
`Compute shader (UpdateShadow): Property (_ShadowMapTexture) at kernel index (0) is not set`

It's unclear to me if that's unexpected. As is noted in UpdateShadow.compute, the use of _SHADOW_COLLECTOR_PASS_ is deprecated, so it might be that _ShadowMapTexture isn't registered in the newest version of deferred rendering?

**Comment by alomo01** [comment] 2020-03-11 01:39
The issue is that __ShadowMapTexture_ isn't getting set up properly in Deferred.

Adding something like this to your primary light should fix this, but it will only pick up shadows from one directional light, and unfortunately not necessarily the one this script is assigned to... I'm not entirely certain the mechanism for that, but this worked for my purposes.

	using UnityEngine;
	using UnityEngine.Rendering;

	[RequireComponent( typeof( Light ) )]
	public class PrimaryLightShadowMapTextureCommandBuffer : MonoBehaviour
	{
		private CommandBuffer commandBuffer;

		void OnEnable()
		{
			commandBuffer = new CommandBuffer();
			RenderTargetIdentifier id = BuiltinRenderTextureType.CurrentActive;
			commandBuffer.SetGlobalTexture( "_ShadowMapTexture", id );
			GetComponent<Light>().AddCommandBuffer( LightEvent.AfterShadowMap, commandBuffer );
		}

		void OnDisable()
		{
			GetComponent<Light>().RemoveCommandBuffer( LightEvent.AfterShadowMap, commandBuffer );
			commandBuffer.Clear();
		}
	}

**Comment by daleeidd** [comment] 2020-07-30 15:10
@alomo01 Thank you for providing that possible fix.

A user on discord mentioned that turning on forward on the camera and then switching back to deferred appears to solves the problem. I tested and it worked for me too. Maybe something in the Unity source code will reveal how forward initialises the _ShadowMapTexture. It is probably similar to the fix provided but might solve the other issue.

**Comment by huwb** [comment] 2021-05-01 12:45
It's unlikely we'll ever get to this, I'm sorry to say, as we do not have the bandwidth.

We're hoping to increase our bandwidth through sponsorship and i wanted to mention that once here in case there is interest in supporting us: https://github.com/sponsors/wave-harmonic . If we gain sponsors on the back of this issue we could try to stretch to hitting it.

**Comment by JJarvis89** [comment] 2021-05-04 06:05
@huwb Thanks for the update.

**Closed** 2021-10-23 01:11 UTC
Labels: bug, help wanted, deferred, BIRP
